"""
AAZHI SATELLITE INTELLIGENCE — Engine 2: Local Cognitive Multimodal Vision AI Engine
Project Aazhi | Autonomous Earth Observation & Tactical Geospatial Command

This module interfaces with the local Ollama instance running `qwen2.5vl:3b`.
It grounds the vision model using deterministic telemetry from Engine 1,
producing decision-ready Earth Observation intelligence reports.
Supports real-time streaming token generation for responsive UI.
"""

import base64
import io
import json
import time
import requests
from typing import Dict, Any, Optional, Generator
from PIL import Image
from .spectral_math import SpectralMetrics, SpectralMathEngine


DEFAULT_OLLAMA_URL = "http://localhost:11434"
DEFAULT_MODEL = "qwen2.5vl:3b"


class VisionAgent:
    """
    Cognitive VLM Agent communicating with local Ollama qwen2.5vl model.
    Optimized for NVIDIA RTX 3050 local GPU acceleration.
    """

    def __init__(self, base_url: str = DEFAULT_OLLAMA_URL, model_name: str = DEFAULT_MODEL):
        self.base_url = base_url.rstrip("/")
        self.model_name = model_name

    def is_available(self) -> bool:
        """
        Checks if the local Ollama service is active and responsive.
        """
        try:
            resp = requests.get(f"{self.base_url}/api/tags", timeout=2)
            return resp.status_code == 200
        except Exception:
            return False

    @staticmethod
    def encode_image_to_base64(image_input, max_dim: int = 896) -> str:
        """
        Encodes a filepath, PIL Image, or bytes to a base64 string for Ollama.
        Smartly resizes massive rasters to optimal visual token resolution (<= 896px)
        to prevent GPU VRAM overflow, avoid context-length overflow, and accelerate inference.
        896px is chosen because qwen2.5vl:3b has a 896x896 native visual token grid.
        """
        if isinstance(image_input, str):
            pil_img = Image.open(image_input)
        elif isinstance(image_input, Image.Image):
            pil_img = image_input
        elif isinstance(image_input, bytes):
            pil_img = Image.open(io.BytesIO(image_input))
        else:
            raise TypeError("Unsupported image type for base64 encoding.")

        if pil_img.mode != "RGB":
            pil_img = pil_img.convert("RGB")

        # Smart downscale if either dimension exceeds max_dim
        w, h = pil_img.size
        if max(w, h) > max_dim:
            scale = max_dim / float(max(w, h))
            new_size = (int(w * scale), int(h * scale))
            pil_img = pil_img.resize(new_size, Image.Resampling.BILINEAR)

        buffer = io.BytesIO()
        pil_img.save(buffer, format="JPEG", quality=85)
        return base64.b64encode(buffer.getvalue()).decode("utf-8")

    def _fallback_report(
        self,
        metrics: SpectralMetrics,
        region_name: str,
        fallow_km2: float = 0.0,
        fallow_pct: float = 0.0,
        fallow_ha: float = 0.0,
    ) -> str:
        """
        Returns a deterministic Engine-1-only intelligence report when the VLM
        fails to produce output. Ensures the UI always shows meaningful data
        rather than a blank screen or a crash.
        """
        cloud_km2 = getattr(metrics, 'cloud_haze_km2', 0.0)
        cloud_pct = getattr(metrics, 'cloud_haze_pct', 0.0)
        return f"""---
### 🛰️ AAZHI-SAT ENGINE-1 DETERMINISTIC INTELLIGENCE REPORT
> *Auto-generated by Engine 1 (Spectral Physics Math) — VLM returned an empty or error response.*
> *Ensure Ollama is running (`ollama serve`) and model `{self.model_name}` is loaded.*

**Region of Interest:** {region_name}

---

### Executive Summary
The target Area of Interest covers **{metrics.total_area_km2} km²** ({metrics.total_area_hectares} Ha | {metrics.total_area_acres} Acres).
Radiometric spectral physics analysis (Engine 1) has been successfully completed with **100% MECE pixel conservation**.

---

### Ground-Truth Telemetry & Conservation Audit

| Land Cover Class | Area (km²) | Coverage (%) | Area (Ha) |
|---|---|---|---|
| 🌿 Active Vegetation | {metrics.vegetation_area_km2} | {metrics.vegetation_coverage_pct}% | {metrics.vegetation_area_hectares} |
| 🟤 Fallow / Dry Soil | {fallow_km2} | {fallow_pct}% | {fallow_ha} |
| 💧 Water & Canals | {metrics.water_area_km2} | {metrics.water_coverage_pct}% | {metrics.water_area_hectares} |
| 🏙️ Built-up / Urban | {metrics.builtup_area_km2} | {metrics.builtup_pct}% | {metrics.builtup_hectares} |
| ☁️ Cloud / Haze | {cloud_km2} | {cloud_pct}% | — |
| **TOTAL** | **{metrics.total_area_km2}** | **100.0%** | **{metrics.total_area_hectares}** |

✅ **Pixel Conservation Verified: 100.0% — Zero unclassified pixels across all land classes.**

---

### Vegetation Health Subclass Analysis
- **Dense Canopy (VARI > 0.28):** {getattr(metrics, 'dense_veg_pct', 0.0)}%
- **Moderate Crops (VARI 0.12–0.28):** {getattr(metrics, 'moderate_veg_pct', 0.0)}%
- **Stressed / Low Vigor (VARI < 0.12):** {getattr(metrics, 'stressed_veg_pct', 0.0)}%
- **Mean Scene VARI Index:** {metrics.mean_veg_index}

---

### Strategic Advisories
1. **🌾 Vegetation Monitoring:** {metrics.vegetation_coverage_pct}% active canopy detected. Cross-reference with seasonal NDVI baseline for crop stress and irrigation sufficiency alerts.
2. **💧 Hydrology Alert:** {metrics.water_coverage_pct}% surface water extent detected. Flag anomalous water body expansion for flood inundation and reservoir overflow risk assessment.
3. **🏙️ Urban Expansion Watch:** {metrics.builtup_pct}% built-up infrastructure coverage. Activate temporal change detection pipeline to monitor encroachment on agricultural buffer zones.

---
> 💡 **To activate full Qwen2.5-VL AI narrative analysis**, ensure Ollama is running: `ollama serve`
> Then load the model: `ollama pull {self.model_name}`
"""

    def generate_intelligence_report_stream(
        self,
        image_input,
        metrics: SpectralMetrics,
        user_query: str = "Generate comprehensive tactical geospatial intelligence report.",
        region_name: str = "Target AOI",
    ) -> Generator[str, None, None]:
        """
        Streams response tokens in real-time from Qwen2.5-VL for smooth typing effect in Streamlit.
        Includes robust error handling for:
        - Empty model responses (the 'model output must contain either output text' error)
        - Ollama engine-level error payloads
        - Connection failures and timeouts
        Always yields at least a deterministic fallback report — the UI never crashes.
        """
        b64_image = self.encode_image_to_base64(image_input)
        math_telemetry = SpectralMathEngine().format_telemetry_prompt(metrics, region_name)

        fallow_km2 = getattr(metrics, 'fallow_soil_area_km2', 0.0)
        fallow_pct = getattr(metrics, 'fallow_soil_pct', 0.0)
        fallow_ha = getattr(metrics, 'fallow_soil_hectares', 0.0)

        # Detect if the user typed a SPECIFIC question or if it's the generic default analysis
        _generic_defaults = {
            "Perform comprehensive geospatial intelligence and hazard analysis on this satellite scene.",
            "Generate comprehensive tactical geospatial intelligence report.",
            "Produce a full formal strategic defense briefing with operational advisories.",
            "Assess active crop parcels, fallow land percentage, and irrigation distribution.",
            "Evaluate surface water bodies, perimeter reservoirs, and flood inundation risk.",
            "Analyze coastal terrain, harbor shipping docks, and transport infrastructure density.",
        }
        _is_custom_question = user_query.strip() not in _generic_defaults and len(user_query.strip()) > 10

        if _is_custom_question:
            # ── USER ASKED A SPECIFIC QUESTION ──────────────────────────────────
            # Force a direct, question-specific answer. DO NOT allow generic descriptions.
            full_prompt = f"""You are AAZHI-SAT AI, a satellite intelligence system analyzing: {region_name}

MEASURED SPECTRAL DATA (Engine 1 Ground Truth):
{math_telemetry}

THE USER IS ASKING: "{user_query}"

STRICT ANSWER RULES — YOU MUST FOLLOW THESE:
1. YOUR VERY FIRST SENTENCE must directly answer the question. Start with "Yes", "No", "There is", "There is no", "The data shows", etc.
2. DO NOT describe the general landscape unless it is directly relevant to answering the question.
3. If the question asks about something NOT detected (e.g. storm, fire, flood) — clearly state it is NOT PRESENT, then briefly explain what the spectral data shows instead.
4. If the question asks about something that IS detected — clearly state it IS PRESENT with the exact measured values as proof.
5. Use ONLY 2-3 short paragraphs. No bullet points. No section headers. No generic report structure.
6. End with one sentence: "Operational status: [your conclusion]."

QUESTION-SPECIFIC GUIDANCE:
- Storm / cyclone / weather? → Check water_pct for flooding. High water + low vegetation may indicate storm damage. If none detected, say clearly: "No storm signature detected."
- Fire / wildfire? → Check fallow_pct (bare/scorched land) and vegetation loss. If none, say "No thermal anomaly or fire signature detected."
- Flood / inundation? → Check water_area_km2 and water_coverage_pct directly.
- Crops / agriculture? → Check vegetation_coverage_pct and fallow_soil_pct.
- Buildings / urban? → Check builtup_pct and builtup_area_km2.

Now answer the user's question directly:"""
        else:
            # ── DEFAULT: FULL STRUCTURED ANALYSIS REPORT ────────────────────────
            # Produce the comprehensive 4-section intelligence report.
            full_prompt = f"""You are AAZHI-SAT AI, an autonomous Earth Observation and tactical remote sensing intelligence platform.

{math_telemetry}

USER MISSION DIRECTIVE:
"{user_query}"

INSTRUCTIONS FOR REPORT GENERATION:
1. ### Executive Summary
   - State the dominant land cover class, physical survey extent, and operational status of the region.
2. ### Ground-Truth Telemetry & Conservation Audit
   - Explicitly cite the 100% accounted surface telemetry:
     - Total Survey Area: {metrics.total_area_km2} km2 ({metrics.total_area_hectares} Ha)
     - Active Vegetation: {metrics.vegetation_area_km2} km2 ({metrics.vegetation_coverage_pct}%)
     - Fallow Soil: {fallow_km2} km2 ({fallow_pct}%)
     - Water: {metrics.water_area_km2} km2 ({metrics.water_coverage_pct}%)
     - Built-up: {metrics.builtup_area_km2} km2 ({metrics.builtup_pct}%)
     - All 5 classes sum to 100% with zero unclassified pixels.
3. ### Geospatial Observations
   - Describe visible land cover, crop parcels, water bodies, and urban zones.
4. ### Strategic Advisories
   - Give 3 concrete operational directives for disaster response, water resources, or agriculture.

Format in clean Markdown with clear headings and bullet points.
"""



        payload = {
            "model": self.model_name,
            "prompt": full_prompt,
            "images": [b64_image],
            "stream": True,
            "options": {
                "temperature": 0.2,
                "top_p": 0.9,
                "num_predict": 900,
            },
        }

        yielded_any = False

        try:
            with requests.post(
                f"{self.base_url}/api/generate",
                json=payload,
                stream=True,
                timeout=120,
            ) as resp:
                resp.raise_for_status()

                for line in resp.iter_lines():
                    if not line:
                        continue

                    try:
                        chunk = json.loads(line.decode("utf-8"))
                    except (json.JSONDecodeError, UnicodeDecodeError):
                        continue

                    # Detect Ollama engine-level error payloads e.g. {"error": "model output error..."}
                    if "error" in chunk:
                        err_msg = chunk["error"]
                        yield f"\n\n⚠️ **Ollama model error:** `{err_msg}`\n\n"
                        yield "> *Showing Engine-1 deterministic report as fallback:*\n\n"
                        yield self._fallback_report(metrics, region_name, fallow_km2, fallow_pct, fallow_ha)
                        return

                    token = chunk.get("response", "")
                    if token:
                        yielded_any = True
                        yield token

                    if chunk.get("done", False):
                        break

        except requests.exceptions.Timeout:
            yield f"\n\n⚠️ **Request timed out** — Qwen2.5-VL took too long. The model may be overloaded or the image resolution is too high.\n\n"
            yield "> *Showing Engine-1 deterministic report as fallback:*\n\n"
            yield self._fallback_report(metrics, region_name, fallow_km2, fallow_pct, fallow_ha)
            return
        except requests.exceptions.ConnectionError:
            yield f"\n\n⚠️ **Cannot connect to Ollama** at `{self.base_url}`.\nPlease run: `ollama serve`\n\n"
            yield self._fallback_report(metrics, region_name, fallow_km2, fallow_pct, fallow_ha)
            return
        except requests.exceptions.RequestException as e:
            yield f"\n\n⚠️ **Error communicating with local Ollama ({self.model_name}):** {e}\n\n"
            yield self._fallback_report(metrics, region_name, fallow_km2, fallow_pct, fallow_ha)
            return

        # If the stream finished but every token was empty — emit fallback
        if not yielded_any:
            yield f"\n\n⚠️ **The model returned an empty response.**\n"
            yield "This usually happens when:\n- The image visual token count exceeds the model's context window\n- The model refused the request (safety filter)\n- VRAM was exhausted mid-generation\n\n"
            yield "> *Showing Engine-1 deterministic report as fallback:*\n\n"
            yield self._fallback_report(metrics, region_name, fallow_km2, fallow_pct, fallow_ha)

    def generate_intelligence_report(
        self,
        image_input,
        metrics: SpectralMetrics,
        user_query: str = "Perform complete geospatial intelligence and hazard analysis on this satellite scene.",
        region_name: str = "Target AOI",
    ) -> str:
        """
        Synchronous batch report generation.
        """
        tokens = list(self.generate_intelligence_report_stream(image_input, metrics, user_query, region_name))
        return "".join(tokens)

    def guess_geolocation(self, image_input) -> tuple[float, float]:
        """
        Attempts to guess the latitude and longitude of an image using Qwen2.5-VL.
        Returns a tuple of (latitude, longitude). If it fails, returns (None, None).
        """
        b64_image = self.encode_image_to_base64(image_input)
        
        prompt = (
            "Analyze the geographical and topographical features in this satellite image "
            "(such as coastlines, rivers, urban layouts, agricultural patterns, or known landmarks). "
            "Based on your visual assessment, output the exact estimated latitude and longitude coordinates "
            "of this location. Format your response strictly as a JSON object: {\"latitude\": 11.667, \"longitude\": 92.735}. "
            "Do not include any other text."
        )

        payload = {
            "model": self.model_name,
            "prompt": prompt,
            "images": [b64_image],
            "stream": False,
            "options": {
                "temperature": 0.1,
                "num_predict": 100,
            },
        }

        try:
            resp = requests.post(f"{self.base_url}/api/generate", json=payload, timeout=60)
            resp.raise_for_status()
            result_text = resp.json().get("response", "")
            
            # Extract JSON from response
            import re
            json_match = re.search(r'\{.*?\}', result_text, re.DOTALL)
            if json_match:
                coords = json.loads(json_match.group(0))
                return float(coords.get("latitude")), float(coords.get("longitude"))
            return None, None
        except Exception:
            return None, None

    def chat_stream(
        self,
        image_input,
        conversation_history: list,
        user_message: str,
        metrics: Optional[SpectralMetrics] = None,
    ) -> Generator[str, None, None]:
        """
        Interactive multi-turn conversational chat with streaming tokens.
        """
        b64_image = self.encode_image_to_base64(image_input)

        context_note = ""
        if metrics:
            fallow_pct = getattr(metrics, 'fallow_soil_pct', 0.0)
            context_note = (
                f"\n[Active Scene Ground-Truth: Total={metrics.total_area_km2}km2, "
                f"Veg={metrics.vegetation_coverage_pct}%, Fallow={fallow_pct}%, "
                f"Water={metrics.water_coverage_pct}%, Builtup={metrics.builtup_pct}% (100% Conserved)]\n"
            )

        prompt = f"System: You are SatQuery AI by Team Aazhi assisting ISRO scientists with Earth Observation.{context_note}\nUser: {user_message}"

        payload = {
            "model": self.model_name,
            "prompt": prompt,
            "images": [b64_image],
            "stream": True,
            "options": {
                "temperature": 0.3,
                "num_predict": 512,
            },
        }

        yielded_any = False
        try:
            with requests.post(f"{self.base_url}/api/generate", json=payload, stream=True, timeout=90) as resp:
                resp.raise_for_status()
                for line in resp.iter_lines():
                    if line:
                        try:
                            chunk = json.loads(line.decode("utf-8"))
                        except (json.JSONDecodeError, UnicodeDecodeError):
                            continue
                        if "error" in chunk:
                            yield f"⚠️ Model error: {chunk['error']}"
                            return
                        token = chunk.get("response", "")
                        if token:
                            yielded_any = True
                            yield token
                        if chunk.get("done", False):
                            break
        except Exception as e:
            yield f"⚠️ Connection error: {e}"
            return

        if not yielded_any:
            yield "⚠️ The model returned an empty response. Please try again or reduce image size."
